#!/bin/bash
if [ -z "$PYFILE" ]; then
   echo "Error: PYFILE environment variable is not set."
   exit 1
fi

python3 -m compileall "$PYFILE" > /dev/null 2>&1
if [ -f "$PYFILEc" ]; then
   echo "Compiling $PYFILE ..."
   cp "$PYFILE" "$PYFILEc"
   exit 0
fi
